import asyncio
from src.env import SERVER
import src.api  # pylint: disable=unused-import

loop = asyncio.get_event_loop()
SERVER.start()
loop.run_forever()

# NOTE TO SELF: PLEASE BE SURE TO PRUNE DOWN THE SIZE AND FREQUENCY OF QUERIES AS MORE
# COMMANDS AND USE-CASES ARE FLESHED OUT TO ENSURE THAT I'M NOT OVERLOADING IT WITH EXCESS
# CACHING OF MASSIVE AMOUNTS OF DATA EVERY FEW MINUTES, BUT INSTEAD ARE ONLY RETRIEVING THE
# DATA THAT IS ACTUALLY REQUIRED FOR MY SERVICE (WHICH WILL MOST LIKELY BE EVERYTHING IN ALL
# HONESTY, SINCE THEN I CAN PROVIDE FREQUENTLY UPDATED STATS AND WHATNOT)
